# Generated by Django 5.2.5 on 2025-12-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishingredient',
            name='amount',
            field=models.CharField(blank=True, max_length=50, verbose_name='Количество'),
        ),
    ]
