# Generated by Django 5.2.5 on 2025-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_info', '0002_alter_dishingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название ингредиента'),
        ),
    ]
