# Generated by Django 5.2.5 on 2025-08-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('slug', models.SlugField(unique=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='dishes/', verbose_name='Фотография блюда')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cooking_time', models.IntegerField(verbose_name='Время приготовления')),
                ('dish_price', models.IntegerField(verbose_name='Стоимость блюда')),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], max_length=10, verbose_name='Сложность приготовления')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
