# Generated by Django 5.2.5 on 2025-09-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюд'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='descr',
            field=models.TextField(blank=True, max_length=150, verbose_name='Описание блюда'),
        ),
    ]
