# Generated by Django 5.2.5 on 2025-08-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='descr',
            field=models.TextField(blank=True, max_length=80, verbose_name='Описание блюда'),
        ),
    ]
